name: Deploy CfP Website

on:
  push:
    branches: [main, cfp]
    paths:
      - "CfPWebsite/**"
      - "SharedModels/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Fly.io
        uses: superfly/flyctl-action/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          cd CfPWebsite
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
